sming-cli:

  build: .

# Uncomment the lines below if you want to use the source code in your host computer
#  volumes:
#    - ../../Sming/:/workspace/Sming/

  ports:
    - "10080:80"

# Modify the line below if you serial adapter is mapped to a different port
  devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"

  volumes:
    - .:/SpeedyBirdie
    - /etc/group:/etc/group:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro


  privileged: true

  working_dir: /SpeedyBirdie
